name: stereoaudiosystems
favicon: null
layout_spectrum: 0.0013264745939522982
typography_spectrum: 0.6986026971135288
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#707173'
    - '#f29400'
    - '#8e8f90'
    - '#bebec0'
  brandStrength: 0.6346642416901886
  lightness: 0.09060411667451262
  saturation: 0.5381144967395812
  rhythmicContrast: 0.9894989868625998
purpose: []
